stages:
  - test
  - quality

before_script:
  - python3.10 --version
  - poetry install --with dev

test-job:
  stage: test
  script:
    - poetry run pytest

quality-job:
  stage: quality
  script:
    - poetry run mypy --strict ch5mpy
