fail_fast: true

repos:
  - repo: https://github.com/ambv/black
    rev: 22.12.0
    hooks:
      - id: black
        language_version: python3.10

  - repo: https://github.com/pycqa/pylint
    rev: v2.15.8
    hooks:
      - id: pylint
        args: [--disable=all, --enable=unused-import]
        language_version: python3.10

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.991
    hooks:
      - id: mypy
        exclude: ^tests/
        args: [--strict]
        additional_dependencies: [numpy==1.23.5]
        language_version: python3.10

#  - repo: local
#    hooks:
#      - id: pytest
#        name: pytest
#        entry: pytest
#        language: system
#        pass_filenames: false
#        always_run: true
